# Assignment 1: Numpy

Perform the follwing tasks:


In [2]:
#3.1: import the numpy library

import numpy as np

In [3]:
#3.2: create a random 10x10 array named A

A = np.random.rand(10,10);

A

array([[0.9620958 , 0.04470566, 0.06147602, 0.85399597, 0.26358935,
        0.38484993, 0.90089912, 0.98066229, 0.4846192 , 0.4924398 ],
       [0.19356903, 0.95748728, 0.2852006 , 0.65949823, 0.35251661,
        0.72935286, 0.94570794, 0.50055846, 0.15827519, 0.47313483],
       [0.64412665, 0.08489237, 0.44193341, 0.56888483, 0.93348617,
        0.5261109 , 0.48562045, 0.37369006, 0.91129473, 0.89241377],
       [0.59921196, 0.73932607, 0.29197299, 0.91588864, 0.85855867,
        0.34425945, 0.48032755, 0.2002888 , 0.01730815, 0.19689719],
       [0.19273718, 0.28537347, 0.59035223, 0.31201928, 0.9000957 ,
        0.03670496, 0.41722059, 0.61114023, 0.95335451, 0.27285487],
       [0.46883746, 0.06179022, 0.09666991, 0.37471843, 0.33445968,
        0.42834488, 0.03556406, 0.43149774, 0.57850469, 0.17199527],
       [0.0101384 , 0.42274194, 0.04926585, 0.21436793, 0.22530181,
        0.41407137, 0.13269875, 0.36806883, 0.74432692, 0.25108108],
       [0.65471187, 0.60237155, 0.1585207

In [5]:
#3.3: return only the odd rows of A

A[0::2]

array([[0.9620958 , 0.04470566, 0.06147602, 0.85399597, 0.26358935,
        0.38484993, 0.90089912, 0.98066229, 0.4846192 , 0.4924398 ],
       [0.64412665, 0.08489237, 0.44193341, 0.56888483, 0.93348617,
        0.5261109 , 0.48562045, 0.37369006, 0.91129473, 0.89241377],
       [0.19273718, 0.28537347, 0.59035223, 0.31201928, 0.9000957 ,
        0.03670496, 0.41722059, 0.61114023, 0.95335451, 0.27285487],
       [0.0101384 , 0.42274194, 0.04926585, 0.21436793, 0.22530181,
        0.41407137, 0.13269875, 0.36806883, 0.74432692, 0.25108108],
       [0.84787367, 0.26860747, 0.90058905, 0.82021811, 0.44897727,
        0.64681414, 0.01488602, 0.05645653, 0.44649138, 0.72138765]])

In [7]:
#3.4: perform a matrix multiplication of A with it's transposed

M = np.dot(A,A.T);

M


array([[4.12897463, 2.83594977, 3.27008089, 2.50295127, 2.32390103,
        1.85303332, 1.39835042, 2.96718642, 2.59123744, 3.51661439],
       [2.83594977, 3.52058158, 2.63275063, 2.71532899, 2.00923369,
        1.27749232, 1.48992311, 2.6547044 , 2.30343869, 3.36379323],
       [3.27008089, 2.63275063, 4.09156194, 2.58095999, 2.98958462,
        1.95989618, 1.71865876, 2.95185764, 3.27194853, 3.88425486],
       [2.50295127, 2.71532899, 2.58095999, 2.99529402, 1.96306953,
        1.28004131, 1.06510245, 2.07637129, 2.4971908 , 3.05242464],
       [2.32390103, 2.00923369, 2.98958462, 1.96306953, 2.90687695,
        1.47574596, 1.49497862, 2.50648995, 2.11873496, 2.96150989],
       [1.85303332, 1.27749232, 1.95989618, 1.28004131, 1.47574596,
        1.22043333, 1.00600599, 1.94124955, 1.64301017, 1.96194295],
       [1.39835042, 1.48992311, 1.71865876, 1.06510245, 1.49497862,
        1.00600599, 1.21955818, 1.91065357, 1.24754467, 1.84064108],
       [2.96718642, 2.6547044 , 2.9518576

In [10]:
#3.5: compute the matrix inverse of A

A_Inv = np.linalg.inv(A)

A_Inv

array([[ 1.08835269, -1.97643853,  0.37290251,  1.10079713, -0.72542294,
        -3.95985167,  1.07715968,  1.40370741,  0.61945864, -0.04384669],
       [ 0.30606292, -0.66370667,  0.27177119,  1.16765661, -0.33577514,
        -2.8548164 ,  1.68562099,  0.87681157,  0.16805286, -0.70292663],
       [-0.23900722,  0.56346559, -0.90416218, -0.82585343,  1.06282362,
         0.24847423, -1.13019307, -0.04643698,  0.93473738,  0.23882735],
       [ 0.20707489,  0.14754601, -1.33103276,  0.02037712,  0.17873922,
         2.02519495,  0.7390359 , -1.43949017,  0.27274099,  0.63842076],
       [-1.07101435,  0.82977574,  1.05128723,  0.30471044,  0.29390534,
         2.42442029, -1.83636251, -0.14172595, -1.00908042, -0.40955798],
       [-1.02466363,  1.35882851, -0.12455081, -0.96476344, -0.32884863,
         3.08379505, -1.56709291, -0.22949238, -0.13371254,  0.52685536],
       [ 0.97639166, -0.97179996, -0.62294998, -0.11734956, -0.01666504,
        -3.35555856,  0.95444468,  0.26430311

In [13]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

np.where(A > 0.5, A/2, A)

array([[0.4810479 , 0.04470566, 0.06147602, 0.42699798, 0.26358935,
        0.38484993, 0.45044956, 0.49033115, 0.4846192 , 0.4924398 ],
       [0.19356903, 0.47874364, 0.2852006 , 0.32974911, 0.35251661,
        0.36467643, 0.47285397, 0.25027923, 0.15827519, 0.47313483],
       [0.32206332, 0.08489237, 0.44193341, 0.28444241, 0.46674308,
        0.26305545, 0.48562045, 0.37369006, 0.45564737, 0.44620688],
       [0.29960598, 0.36966304, 0.29197299, 0.45794432, 0.42927934,
        0.34425945, 0.48032755, 0.2002888 , 0.01730815, 0.19689719],
       [0.19273718, 0.28537347, 0.29517611, 0.31201928, 0.45004785,
        0.03670496, 0.41722059, 0.30557011, 0.47667726, 0.27285487],
       [0.46883746, 0.06179022, 0.09666991, 0.37471843, 0.33445968,
        0.42834488, 0.03556406, 0.43149774, 0.28925234, 0.17199527],
       [0.0101384 , 0.42274194, 0.04926585, 0.21436793, 0.22530181,
        0.41407137, 0.13269875, 0.36806883, 0.37216346, 0.25108108],
       [0.32735593, 0.30118578, 0.1585207